### ISSUE TITLE
hashwithindifferentaccess is messing up my application

### ISSUE THREAD

**Issue by nikolalsvk** [alexpeattie/nitlink#1]
Hi there,

I stumbled upon your gem trying to parse 'Link' headers from GitHub responses, but `hashwithindifferentaccess` dependency is making my tests fail since we don't yet support hashes with indifferent access.

Is there any way I can work around this, or if you could change it not to use that gem 🙇?

**Comment by alexpeattie** [comment]
Hi Nikola, yep I can definitely take a look at that 😊. Could you give more
details about why it causes the test to fail? Is it simply the inclusion of
the gem which causes the failures?

**Comment by nikolalsvk** [comment]
Thanks for the quick response @alexpeattie!

>  Is it simply the inclusion of the gem which causes the failures?

Well yeah, just the inclusion breaks the stuff.

> Could you give more details about why it causes the test to fail?

I can give you one example, it breaks accessing my params

```
Failure/Error: params.permit(*ATTRIBUTES)

     NoMethodError:
       undefined method `each' for nil:NilClass
```

P.S. I ended up writing a parser for Link header, but would use yours if you get a chance to fix it :)

P.P.S Maybe I take a shot at making it not rely on `hashwithindifferentaccess` gem

**Comment by alexpeattie** [comment]
I've had a go at inlining the `HashWithIndifferentAccess` implementation within Nitlink (this is how [Thor](https://github.com/erikhuda/thor/blob/master/lib/thor/core_ext/hash_with_indifferent_access.rb) does it for e.g.). I'm pretty sure it shouldn't interfere with anything now.

It's on the `dev` branch - mind giving it a whirl?:

```ruby
# In Gemfile
gem 'nitlink', github: 'alexpeattie/nitlink', branch: 'dev'
```

**Comment by nikolalsvk** [comment]
@alexpeattie hashwithindifferentaccess is not causing any tests to fail now, thanks 🙇 

I have one more problem, I'll open another issue.

**Comment by nikolalsvk** [comment]
@alexpeattie do you plan to make this an official release?

**Comment by alexpeattie** [comment]
Yes indeed, will update the tests documentation etc. and aim to release today or tomorrow 👍

**Comment by alexpeattie** [comment]
Released now, let me know if it's all working well and I'll close this 😃

**Comment by nikolalsvk** [comment]
It's working 🎉 

P.S. Ever thought about writing a blog post or just putting this gem somewhere to be noticed? e.g. [Hacker News](https://news.ycombinator.com/) or [RubyFlow](http://www.rubyflow.com/)

**Comment by alexpeattie** [comment]
Yep, good idea, I'll try and put together a blog post in the next couple of weeks 👍 .

Thanks for your help w/ this issue, closing it out!
